### ISSUE TITLE
Practice Feature Tracking v0.1

### ISSUE THREAD

**Issue by AkmalFairuz** [AkmalFairuz/df-practice#1]
#### Match System

- [x] Find Match Queue
- [x] Map
- [x] Game
   - [x] GameManager
   - [ ] Team
   - [x] Handler

#### Gamemode

- [x] Duels
   - [x] NoDebuff
   - [x] Classic
   - [ ] Sumo
   - [ ] Build
   - [ ] BedFight
   - [ ] TopFight
- [x] Free for All (FFA)
   - [x] Sumo
   - [x] NoDebuff
   - [x] Build
   - [x] Classic  

#### Core

- [ ] Ranks
- [ ] Tebex Integration
- [ ] Cosmetic
   - [ ] Wings
   - [ ] Cape
   - [ ] Particle
   - [ ] Projectile Particle
- [ ] Vote Reward
- [x] Lobby
- [ ] Global Chat System
- [x] Private Message (/msg, /w)
   - [x] Reply Command (/r)
- [ ] Statistics
- [x] Moderation System
   - [x] Chat cooldown
   - [ ] Badword filter
   - [x] Ban
   - [ ] Mute
   - [ ] Kick
   - [ ] Freeze
   - [ ] Alias
   - [ ] Spectating
   - [x] Admin/Staff Permissions
- [ ] Anti Interrupt

#### Others
- [x] Change player gamemode command
- [x] Teleport command
- [x] /duel command
- [x] No Damage Ender Pearl
- [x] Multi-version support (1.20.80-1.21.50) via <a href="https://github.com/AkmalFairuz/legacy-version">AkmalFairuz/legacy-version</a>
